# 実行環境に関する設定
environment:
  seed: 42
  device: 'auto' # 'auto', 'cpu', 'cuda'などを指定

# データに関する設定
data:
  name: 'synthetic_2d'
  n_samples: 100
  n_features: 2

# モデルのアーキテクチャに関する設定
model:
  name: 'MLP'
  input_dim: 2
  hidden_dim: 16
  output_dim: 1

# 訓練に関する設定
training:
  optimizer: 'Adam'
  learning_rate: 0.01
  epochs: 1000
  criterion: 'BCEWithLogitsLoss'
  